// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpk3dkiHFUhA7SQ126uWvRKcoXChbR5pM',
    appId: '1:821836479428:web:c66cfec3593b92e5244291',
    messagingSenderId: '821836479428',
    projectId: 'english-study-project',
    authDomain: 'english-study-project.firebaseapp.com',
    storageBucket: 'english-study-project.appspot.com',
    measurementId: 'G-1XK4YDY0BB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCU0pxMMEsgWVFY8hftxatcES1wTTQ_R7M',
    appId: '1:821836479428:android:616acd337c1cb68d244291',
    messagingSenderId: '821836479428',
    projectId: 'english-study-project',
    storageBucket: 'english-study-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAgG9eMmL8SDsiIZWKvzrVODi6fixavHsk',
    appId: '1:821836479428:ios:4bb66e653b0abfc2244291',
    messagingSenderId: '821836479428',
    projectId: 'english-study-project',
    storageBucket: 'english-study-project.appspot.com',
    androidClientId: '821836479428-3h7e8ee5rq67h70hcn4dl43srj5be28u.apps.googleusercontent.com',
    iosClientId: '821836479428-1ugoboj6qmka8bf0vjt7juthub5tiasa.apps.googleusercontent.com',
    iosBundleId: 'com.alicsnet.alicsnetApp',
  );
}
